//
//  AppInfo.swift
//  Simple Phone
//
import Foundation

let AppLinks: [String: String] = [
    "1Password": "onepassword://",
    "2Do": "twodo://",
    "8 Ball Pool": "com.miniclip.8ballpoolmult://",
    "AirPlay Receiver": "airplayreceiver-private://",
    "AirPlay Sender UI": "airplay://",
    "Alchemy": "alchemymob://",
    "AlienBlue": "alienblue://",
    "Amount": "amount://",
    "AnaMini": "AnaphobiaMiniNew.audiobus://",
    "Angry Birds": "angrybirds-seasons://",
    "Angry Birds 2": "com.rovio.baba://",
    "Animoog": "Animoog-iPhone://",
    "Any.do": "anydo://",
    "Anytune": "anytune://",
    "App Store": "itms-apps://",
    "Apple Feedback": "applefeedback://",
    "Apple Store": "applestore://",
    "AppCake": "appcake://",
    "AudioCopy": "audiocopyapp://",
    "AudioShare": "audioshare://",
    "Authentication Services UI": "fido://",
    "Auto-Tune": "AutoTune.audiobus://",
    "AutoRap": "smuleautorap://",
    "Bank of America": "bofa://",
    "Beatwave": "beatwave://",
    "BIAS": "positivegridbias://",
    "BitWiz": "bitwiz://",
    "Books": "ibooks://",
    "Burner": "burner://",
    "Byword": "byword://",
    "Calculator": "calc://",
    "Calendar": "calshow://",
    "Camera": "camera://",
    "Camera+": "cameraplus://",
    "Cameo": "cameo-app://",
    "Capital One": "capitalone://",
    "Car Logbook": "carlogbook://",
    "Chrome": "googlechrome://",
    "Clips": "clips://",
    "Clear": "clearapp://",
    "Clock": "clock-alarm://",
    "CodeHub": "codehub://",
    "Codecademy": "codecademy://",
    "Command-C": "command-c://",
    "Contacts": "contacts://",
    "Countdown": "countdown://",
    "Cydia": "cydia://",
    "Daedalus": "daedalus://",
    "Dark Sky": "darksky://",
    "Day One": "dayone://",
    "DeskConnect": "deskconnect://",
    "Diagnostics": "diagnostics://",
    "Dictation": "fb112953085413703://",
    "djay 2": "djay://",
    "DO Button": "dobutton://",
    "DO Camera": "docamera://",
    "DO Note": "donote://",
    "Docs": "googledocs://",
    "Dolphin": "dolphin://",
    "Domino's": "dominos://",
    "Drafts": "drafts4://",
    "Drive": "googledrive://",
    "Dropbox": "db-auth://",
    "Editorial": "editorial://",
    "Endless": "endlesshttp://",
    "Esurance": "esuios://",
    "Evernote": "evernote://",
    "Expenses OK": "expensesok://",
    "FaceTime": "facetime://",
    "Facebook": "fb://",
    "Facebook Groups": "fb-groups://",
    "Facebook Messenger": "fb-messenger://",
    "Face Swap Me": "fb508586409152169://",
    "Facetune": "facetune://",
    "Family": "family://",
    "Feedly": "feedly://",
    "Figure": "phfigure://",
    "Files": "shareddocuments://",
    "Find My": "findmy://",
    "Fing": "fing://",
    "Fit Brains": "fitbrains-trainer://",
    "Fitness": "fitnessapp://",
    "FL Studio Mobile": "flstudiomobilehd://",
    "Flashlight": "ihandyflashlightledpro://",
    "Flickr": "flickr://",
    "Flixster Video": "flxvid://",
    "Freeform": "freeform://",
    "GarageBand": "garageband://",
    "Giffer": "giffer://",
    "Gmail": "googlegmail://",
    "GO Launcher": "GOLauncher://",
    "Google Authenticator": "googleauthenticator://",
    "Google Earth": "comgoogleearth://",
    "Google Maps": "comgooglemaps://",
    "GoodReader": "ghttp://",
    "Groups": "fb-groups://",
    "Handle": "handle://",
    "Health": "x-apple-health://",
    "HISTORY Here": "historyhere://",
    "Home": "x-hm://",
    "Hulu": "hulu://",
    "I Am T-Pain": "tpain://",
    "iCab Mobile": "icabmobile://",
    "IF": "ifttt://",
    "iFile": "ifile://",
    "iMaschine": "iMaschine://",
    "iMovie": "imovie://",
    "improVox": "improVox://",
    "Instagram": "instagram://",
    "iTranslate": "iTranslate://",
    "iTranslate Voice": "itranslatevoice://",
    "iTunes Store": "itms://",
    "iTunes U": "itunesu://",
    "iZip": "ComcsoftAppsRecieveriZip://",
    "JamUp Pro": "jamuppro://",
    "jsany": "jsany://",
    "Jump Desktop": "jump://",
    "Juxtaposer": "juxtaposer://",
    "Keynote": "x-keynote-live://",
    "Khan Academy": "khanacademy://",
    "Kik": "kik://",
    "Launcher": "launcher://",
    "Launch Center Pro": "launch://",
    "Learn Java": "LearnJava://",
    "Learn JavaScript": "LearnJava://",
    "Learn Python": "udemy-python://",
    "Learn SQL": "LearnSQL://",
    "Line2": "line2://",
    "Listacular": "listacular://",
    "LIFTTT": "lifttt://",
    "Loopy HD": "loopy-hd://",
    "Magisto": "magisto://",
    "Mail": "message://",
    "Maps": "maps://",
    "MConverter": "db-30j6esahg12o7lq://",
    "Messages": "messages://",
    "Midiflow": "midiflow-preset://",
    "MindNode": "mindnode://",
    "miniSynth 2": "miniSynth2://",
    "MLauncher": "mlauncher://",
    "Music": "music://",
    "Music Studio": "musicstudiolite://",
    "My Media": "fb457262524303247://",
    "Netflix": "nflx://",
    "News": "applenews://",
    "Nocs": "nocs://",
    "Notability": "NotabilityBoxLogin://",
    "Notes": "mobilenotes://",
    "NPR One": "nprone://",
    "Numbers": "com.apple.iwork.numbers-share://",
    "Numflix": "numflix://",
    "Office Lens": "launch-OfficeLens://",
    "OneNote": "onenote://",
    "Oscillator": "oscillator1.audiobus://",
    "OSnap!": "osnapphotoapp://",
    "Overcast": "overcast://",
    "Pages": "fb-pma://",
    "Pandora": "pandora://",
    "Path": "path://",
    "Path on": "pathon://",
    "PDFpen Scan+": "pdfpenscan://",
    "Phone": "mobilephone://",
    "PhotoGrid": "com.YunFang.PhotoGrid://",
    "Photos": "photos-redirect://",
    "Picup": "fileupload://",
    "Plain Text": "iacplaintext://",
    "Plex": "plexapp://",
    "Pocket Cloud": "pocketcloudpartner://",
    "Podcasts": "podcasts://",
    "PowerPoint": "powerpoint://",
    "Preguntados": "preguntados://",
    "Print Center": "appleprintcenter://",
    "Prompt": "prompt-ssh://",
    "Puffin": "puffin://",
    "Pythonista": "pythonista://",
    "QR Reader": "qr://",
    "Red Laser": "redlaser://",
    "Remote": "remote://",
    "Remote Mouse": "RemoteMouse://",
    "Reminders": "x-apple-reminder://",
    "Remaster": "Remaster130.audiobus://",
    "RoboVox": "RoboVox-1.6.8.audiobus://",
    "Runtastic": "at.runtastic.runtastic.pro://",
    "Safari": "x-web-search://",
    "Slack": "slack://",
    "Scan & Translate": "db-5bvxfkv01svq3bp://",
    "Screens": "screens://",
    "Settings": "app-prefs://",
    "Shazam": "shazam://",
    "Short Menu": "short-menu://",
    "Shortcuts": "shortcuts://",
    "SimpleMind": "fb170956139584666://",
    "Simplenote": "simplenote://",
    "Sing!": "smulesing://",
    "Singaling": "Singaling.1.1.audiobus://",
    "SLauncher": "launcherpro://",
    "Sleep Cycle": "sc1337://",
    "Smeego": "smeegoapp://",
    "SoundCloud": "soundcloud://",
    "Speak & Translate": "translatorfreenew://",
    "Spotify": "spotify://",
    "Star Walk": "starwalk://",
    "Star Walk 2": "starwalk2://",
    "Strava": "strava://record/new/start",
    "Stocks": "stocks://",
    "StumbleUpon": "stumbleupon://",
    "Sun Vox": "SunVox.audiobus://",
    "Super Note": "fb287841191366653://",
    "Support": "applesupport://",
    "Sweet MIDI": "db-9msy0x2b3tfo0mo://",
    "Syfy": "syfytve://",
    "Symbols": "symbolay://",
    "Tally": "tally2://",
    "Tarteel": "tarteel://",
    "TED Books": "tedbooks://",
    "TestFlight": "itms-beta://",
    "TextExpander": "tetouch://",
    "Text Tool": "texttool://",
    "The Weather Channel": "twc://",
    "Things": "things://",
    "Timehop": "timehop://",
    "Timer": "launchtimer://",
    "Tips": "x-tips-widget://",
    "Tiny Piano": "squarepoet.tinypiano://",
    "Tone Generator": "fb199649273430005://",
    "TV": "videos://",
    "TV Remote": "tvremote://",
    "Tumblr": "tumblr://",
    "Twitter": "twitter://",
    "Twerker": "twerker://",
    "VidFX": "VideoMergerPro://",
    "Vidlab": "vidlab://",
    "Vidme": "vidme://",
    "VICE News": "vicenews://",
    "Vio": "vio://",
    "VLC": "vlc://",
    "VNC Viewer": "vnc://",
    "Voice Memos": "voicememos://",
    "Vocal Live": "vocalive://",
    "VUDU Player": "vuduiosplayer://",
    "Wallet": "shoebox://",
    "Walkmeter": "abvio-walkmeter://",
    "Watch": "watchface://",
    "WhatsApp": "whatsapp://mobile/16503158158",
    "Word": "ms-word://",
    "Workflow": "workflow://",
    "Xynthesizr": "Xynthesizr://",
    "Yelp": "yelp://",
    "You Doodle": "youdoodle-1://",
    "YouTube": "youtube://"
]

//
//  SearchBar.swift
//  Minimal
//
//  Created by Iman Morshed on 8/26/24.
//
